# Generated by Django 3.2.13 on 2022-07-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220701_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
